import { AutoComplete } from './AutoComplete'
import { PopOver } from './PopOver'
import { useYoutubePlayerContext } from './YoutubePlayer'
import { CheckIcon, PlayIcon, XMarkIcon } from './icons'
import './EditViewPopOverMenu.css'
import { useRef, useState } from 'react'
