export default {
  AUDIO_ANALYSES_YOUTUBE_VIDEO_NOT_FOUND: 'AUDIO_ANALYSES_YOUTUBE_VIDEO_NOT_FOUND',
  AUDIO_ANALYSES_NOT_FOUND: 'AUDIO_ANALYSES_NOT_FOUND',
  AUDIO_ANALYSES_ALREADY_ANALYZED: 'AUDIO_ANALYSES_ALREADY_ANALYZED'
}
